# Generated by Django 6.0.5 on 2026-05-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_club_manager',
            field=models.BooleanField(default=False, verbose_name='مدیر باشگاه'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_instructor',
            field=models.BooleanField(default=False, verbose_name='مربی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_super_manager',
            field=models.BooleanField(default=False, verbose_name='مدیر کل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='نام\u200cخانوادگی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, unique=True, verbose_name='شماره همراه'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش'),
        ),
    ]
