# Generated by Django 6.0.5 on 2026-05-22 05:37

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0003_sport_club_sports'),
        ('students', '0004_student_sport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ (تومان)')),
                ('expense_date', django_jalali.db.models.jDateField(verbose_name='تاریخ پرداخت')),
                ('category', models.CharField(choices=[('rent', 'اجاره'), ('salary', 'حقوق'), ('equipment', 'تجهیزات'), ('utility', 'قبض'), ('other', 'متفرقه')], default='other', max_length=20, verbose_name='دسته\u200cبندی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='clubs.club', verbose_name='باشگاه')),
            ],
            options={
                'verbose_name': 'پرداختی',
                'verbose_name_plural': 'پرداختی\u200cها',
                'ordering': ['-expense_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ (تومان)')),
                ('payment_date', django_jalali.db.models.jDateField(verbose_name='تاریخ پرداخت')),
                ('month', models.CharField(max_length=20, verbose_name='ماه متناظر')),
                ('method', models.CharField(choices=[('cash', 'نقدی'), ('card', 'کارت'), ('online', 'آنلاین'), ('other', 'سایر')], default='cash', max_length=10, verbose_name='روش پرداخت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='students.student', verbose_name='هنرجو')),
            ],
            options={
                'verbose_name': 'دریافتی',
                'verbose_name_plural': 'دریافتی\u200cها',
                'ordering': ['-payment_date'],
            },
        ),
    ]
