# Generated by Django 6.0.6 on 2026-06-07 19:57

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('students', '0008_student_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeDue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(help_text='مثلاً: ۱۴۰۴/۰۳', max_length=20, verbose_name='ماه')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='مبلغ (تومان)')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شد؟')),
                ('paid_at', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_dues', to='students.student')),
            ],
            options={
                'verbose_name': 'سررسید شهریه',
                'verbose_name_plural': 'سررسیدهای شهریه',
                'unique_together': {('student', 'month')},
            },
        ),
    ]
