# Generated by Django 6.0.6 on 2026-06-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_feedue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedue',
            name='month',
            field=models.CharField(help_text='مثلاً: 1404/03', max_length=7, verbose_name='ماه'),
        ),
    ]
