# Generated by Django 6.0.5 on 2026-05-17 03:53

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('student_code', models.CharField(max_length=20, unique=True)),
                ('current_belt', models.CharField(choices=[('white', 'سفید'), ('yellow', 'زرد'), ('orange', 'نارنجی'), ('green', 'سبز'), ('blue', 'آبی'), ('red', 'قرمز'), ('black_1', 'دان ۱'), ('black_2', 'دان ۲'), ('black_3', 'دان ۳'), ('black_4', 'دان ۴'), ('black_5', 'دان ۵')], default='white', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='clubs.club')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'هنرجو',
                'verbose_name_plural': 'هنرجوها',
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', django_jalali.db.models.jDateField()),
                ('expiry_date', django_jalali.db.models.jDateField()),
                ('insurance_code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='students.student')),
            ],
            options={
                'verbose_name': 'بیمه',
                'verbose_name_plural': 'بیمه\u200cها',
                'ordering': ['-expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('contact_type', models.CharField(choices=[('parent', 'والدین'), ('emergency', 'اضطراری'), ('other', 'سایر')], default='parent', max_length=20)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='students.student')),
            ],
            options={
                'verbose_name': 'شماره تماس',
                'verbose_name_plural': 'شماره\u200cهای تماس',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField()),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غیبت'), ('late', 'تأخیر')], default='present', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student')),
            ],
            options={
                'verbose_name': 'حضور',
                'verbose_name_plural': 'حضور و غیاب',
                'ordering': ['-date'],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
