# Generated by Django 6.0.6 on 2026-06-08 15:21

import django.db.models.deletion
import django_jalali.db.models
import jdatetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام کلاس')),
                ('gender', models.CharField(choices=[('male', 'آقایان'), ('female', 'بانوان'), ('mixed', 'مختلط')], default='mixed', max_length=10, verbose_name='جنسیت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_groups', to='clubs.club', verbose_name='باشگاه')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_groups', to='clubs.sport', verbose_name='رشته ورزشی')),
            ],
            options={
                'verbose_name': 'کلاس',
                'verbose_name_plural': 'کلاس\u200cها',
                'ordering': ['club', 'sport', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثال: صبح ۸ تا ۱۰', max_length=200, verbose_name='نام شیفت')),
                ('days', models.CharField(help_text='مثال: شنبه، دوشنبه', max_length=200, verbose_name='روزها')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='students.classgroup', verbose_name='کلاس')),
            ],
            options={
                'verbose_name': 'شیفت',
                'verbose_name_plural': 'شیفت\u200cها',
                'ordering': ['class_group', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('address', models.TextField(blank=True, null=True, verbose_name='نشانی')),
                ('student_code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='کد هنرجویی')),
                ('current_belt', models.CharField(choices=[('white', 'سفید'), ('yellow', 'زرد'), ('orange', 'نارنجی'), ('green', 'سبز'), ('blue', 'آبی'), ('red', 'قرمز'), ('black', 'مشکی'), ('black_1', 'دان ۱'), ('black_2', 'دان ۲'), ('black_3', 'دان ۳'), ('black_4', 'دان ۴'), ('black_5', 'دان ۵')], default='white', max_length=20, verbose_name='کمربند فعلی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('joined_at', django_jalali.db.models.jDateField(default=jdatetime.date.today, verbose_name='تاریخ عضویت')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='clubs.club', verbose_name='باشگاه')),
                ('sport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='clubs.sport', verbose_name='رشته ورزشی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'هنرجو',
                'verbose_name_plural': 'هنرجوها',
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', django_jalali.db.models.jDateField(verbose_name='تاریخ شروع')),
                ('expiry_date', django_jalali.db.models.jDateField(verbose_name='تاریخ انقضا')),
                ('insurance_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد بیمه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='students.student', verbose_name='هنرجو')),
            ],
            options={
                'verbose_name': 'بیمه',
                'verbose_name_plural': 'بیمه\u200cها',
                'ordering': ['-expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('contact_type', models.CharField(choices=[('parent', 'والدین'), ('emergency', 'اضطراری'), ('other', 'سایر')], default='parent', max_length=20, verbose_name='نوع تماس')),
                ('label', models.CharField(blank=True, max_length=100, null=True, verbose_name='برچسب')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='students.student', verbose_name='هنرجو')),
            ],
            options={
                'verbose_name': 'شماره تماس',
                'verbose_name_plural': 'شماره\u200cهای تماس',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', django_jalali.db.models.jDateField(default=jdatetime.date.today, verbose_name='تاریخ ثبت\u200cنام')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('monthly_fee', models.PositiveIntegerField(default=0, verbose_name='شهریه ماهانه (تومان)')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='students.shift', verbose_name='شیفت')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student', verbose_name='هنرجو')),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام',
                'verbose_name_plural': 'ثبت\u200cنام\u200cها',
                'unique_together': {('student', 'shift')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غیبت'), ('late', 'تأخیر')], default='present', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='students.shift', verbose_name='شیفت')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student', verbose_name='هنرجو')),
            ],
            options={
                'verbose_name': 'حضور و غیاب',
                'verbose_name_plural': 'حضور و غیاب\u200cها',
                'ordering': ['-date'],
                'unique_together': {('student', 'shift', 'date')},
            },
        ),
    ]
