# Generated by Django 6.0.5 on 2026-05-17 04:51

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_alter_clubmembership_options'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date'], 'verbose_name': 'حضور و غیاب', 'verbose_name_plural': 'حضور و غیاب\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'هنرجو', 'verbose_name_plural': 'هنرجویان'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='note',
        ),
        migrations.AddField(
            model_name='student',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='یادداشت'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'حاضر'), ('absent', 'غیبت'), ('late', 'تأخیر')], default='present', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student', verbose_name='هنرجو'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='expiry_date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ انقضا'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='insurance_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کد بیمه'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='start_date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='students.student', verbose_name='هنرجو'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='student',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='clubs.club', verbose_name='باشگاه'),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_belt',
            field=models.CharField(choices=[('white', 'سفید'), ('yellow', 'زرد'), ('orange', 'نارنجی'), ('green', 'سبز'), ('blue', 'آبی'), ('red', 'قرمز'), ('black_1', 'دان ۱'), ('black_2', 'دان ۲'), ('black_3', 'دان ۳'), ('black_4', 'دان ۴'), ('black_5', 'دان ۵')], default='white', max_length=20, verbose_name='کمربند فعلی'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='student',
            name='joined_at',
            field=django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ عضویت'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='کد هنرجویی'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='studentcontact',
            name='contact_type',
            field=models.CharField(choices=[('parent', 'والدین'), ('emergency', 'اضطراری'), ('other', 'سایر')], default='parent', max_length=20, verbose_name='نوع تماس'),
        ),
        migrations.AlterField(
            model_name='studentcontact',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='برچسب'),
        ),
        migrations.AlterField(
            model_name='studentcontact',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='studentcontact',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='students.student', verbose_name='هنرجو'),
        ),
    ]
