# Generated by Django 6.0.5 on 2026-05-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_attendance_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_code',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='کد هنرجویی'),
        ),
    ]
