# Generated by Django 6.0.5 on 2026-05-18 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_sport_club_sports'),
        ('students', '0003_alter_student_student_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='clubs.sport', verbose_name='رشته ورزشی'),
        ),
    ]
