# Generated by Django 6.0.5 on 2026-05-27 06:34

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_sport_club_sports'),
        ('students', '0004_student_sport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'هنرجو', 'verbose_name_plural': 'هنرجوها'},
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام کلاس')),
                ('gender', models.CharField(choices=[('male', 'آقایان'), ('female', 'بانوان'), ('mixed', 'مختلط')], default='mixed', max_length=10, verbose_name='جنسیت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_groups', to='clubs.club', verbose_name='باشگاه')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_groups', to='clubs.sport', verbose_name='رشته ورزشی')),
            ],
            options={
                'verbose_name': 'کلاس',
                'verbose_name_plural': 'کلاس\u200cها',
                'ordering': ['club', 'sport', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثال: صبح ۸ تا ۱۰', max_length=200, verbose_name='نام شیفت')),
                ('days', models.CharField(help_text='مثال: شنبه، دوشنبه', max_length=200, verbose_name='روزها')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='students.classgroup', verbose_name='کلاس')),
            ],
            options={
                'verbose_name': 'شیفت',
                'verbose_name_plural': 'شیفت\u200cها',
                'ordering': ['class_group', 'start_time'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='students.shift', verbose_name='شیفت'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'shift', 'date')},
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ ثبت\u200cنام')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('monthly_fee', models.PositiveIntegerField(default=0, verbose_name='شهریه ماهانه (تومان)')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student', verbose_name='هنرجو')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='students.shift', verbose_name='شیفت')),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام',
                'verbose_name_plural': 'ثبت\u200cنام\u200cها',
                'unique_together': {('student', 'shift')},
            },
        ),
    ]
