# Generated by Django 6.0.5 on 2026-05-29 05:23

import django_jalali.db.models
import jdatetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_options_classgroup_shift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enrolled_at',
            field=django_jalali.db.models.jDateField(default=jdatetime.date.today, verbose_name='تاریخ ثبت\u200cنام'),
        ),
    ]
