# Generated by Django 6.0.5 on 2026-05-29 06:22

import django_jalali.db.models
import jdatetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_enrollment_enrolled_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_belt',
            field=models.CharField(choices=[('white', 'سفید'), ('yellow', 'زرد'), ('orange', 'نارنجی'), ('green', 'سبز'), ('blue', 'آبی'), ('red', 'قرمز'), ('black', 'مشکی'), ('black_1', 'دان ۱'), ('black_2', 'دان ۲'), ('black_3', 'دان ۳'), ('black_4', 'دان ۴'), ('black_5', 'دان ۵')], default='white', max_length=20, verbose_name='کمربند فعلی'),
        ),
        migrations.AlterField(
            model_name='student',
            name='joined_at',
            field=django_jalali.db.models.jDateField(default=jdatetime.date.today, verbose_name='تاریخ عضویت'),
        ),
    ]
