# Generated by Django 6.0.5 on 2026-05-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_student_current_belt_alter_student_joined_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='نشانی'),
        ),
    ]
