# Generated by Django 6.0.5 on 2026-05-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_name', models.CharField(default='باشگاه ستاره\u200cها', max_length=200, verbose_name='نام مجموعه')),
                ('gym_type', models.CharField(default='هاپکیدو', max_length=100, verbose_name='سبک اصلی')),
            ],
            options={
                'verbose_name': 'تنظیمات',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
    ]
