# Generated by Django 6.0.6 on 2026-06-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_name', models.CharField(default='آرنیکا', max_length=200, verbose_name='نام مجموعه')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='لوگو')),
                ('central_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تماس مرکزی')),
                ('central_address', models.TextField(blank=True, null=True, verbose_name='آدرس مرکزی')),
                ('about_text', models.TextField(blank=True, null=True, verbose_name='درباره ما')),
                ('working_hours', models.CharField(blank=True, help_text='مثال: ۸ صبح تا ۱۰ شب', max_length=200, null=True, verbose_name='ساعات کاری')),
                ('rules_text', models.TextField(blank=True, null=True, verbose_name='شرایط عضویت')),
            ],
            options={
                'verbose_name': 'تنظیمات',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('bale', 'بله'), ('eitaa', 'ایتا'), ('rubika', 'روبیکا'), ('youtube', 'یوتیوب'), ('telegram', 'تلگرام'), ('whatsapp', 'واتساپ'), ('website', 'وب\u200cسایت'), ('instagram', 'اینستاگرام'), ('other', 'سایر')], default='other', max_length=20, verbose_name='پلتفرم')),
                ('label', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان نمایشی')),
                ('url', models.CharField(max_length=500, verbose_name='لینک')),
            ],
            options={
                'verbose_name': 'رسانه اجتماعی',
                'verbose_name_plural': 'رسانه\u200cهای اجتماعی',
                'ordering': ['platform'],
            },
        ),
    ]
