# Generated by Django 6.0.5 on 2026-05-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='gym_type',
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='central_address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس مرکزی'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='central_phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تماس مرکزی'),
        ),
    ]
