# Generated by Django 6.0.5 on 2026-05-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_sitesetting_gym_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='لوگو'),
        ),
    ]
