# Generated by Django 6.0.5 on 2026-05-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesetting_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='about_text',
            field=models.TextField(blank=True, null=True, verbose_name='درباره ما'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='اینستاگرام'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='rules_text',
            field=models.TextField(blank=True, null=True, verbose_name='شرایط عضویت'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='telegram',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='تلگرام'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='وب\u200cسایت'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='working_hours',
            field=models.CharField(blank=True, help_text='مثال: ۸ صبح تا ۱۰ شب', max_length=200, null=True, verbose_name='ساعات کاری'),
        ),
    ]
