# Generated by Django 6.0.5 on 2026-05-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesetting_about_text_sitesetting_instagram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'اینستاگرام'), ('telegram', 'تلگرام'), ('whatsapp', 'واتساپ'), ('youtube', 'یوتیوب'), ('website', 'وب\u200cسایت'), ('other', 'سایر')], default='other', max_length=20, verbose_name='پلتفرم')),
                ('label', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان نمایشی')),
                ('url', models.CharField(max_length=500, verbose_name='لینک')),
            ],
            options={
                'verbose_name': 'شبکه اجتماعی',
                'verbose_name_plural': 'شبکه\u200cهای اجتماعی',
                'ordering': ['platform'],
            },
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='website',
        ),
    ]
