# Generated by Django 6.0.5 on 2026-05-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sociallink_remove_sitesetting_instagram_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallink',
            options={'ordering': ['platform'], 'verbose_name': 'رسانه اجتماعی', 'verbose_name_plural': 'رسانه\u200cهای اجتماعی'},
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='gym_name',
            field=models.CharField(default='آرنیکا', max_length=200, verbose_name='نام مجموعه'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('bale', 'بله'), ('eitaa', 'ایتا'), ('rubika', 'روبیکا'), ('youtube', 'یوتیوب'), ('telegram', 'تلگرام'), ('whatsapp', 'واتساپ'), ('website', 'وب\u200cسایت'), ('instagram', 'اینستاگرام'), ('other', 'سایر')], default='other', max_length=20, verbose_name='پلتفرم'),
        ),
    ]
