# Generated by Django 6.0.5 on 2026-05-17 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubmembership',
            options={'verbose_name': 'عضو', 'verbose_name_plural': 'عضوها'},
        ),
    ]
