# Generated by Django 6.0.5 on 2026-05-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_alter_clubmembership_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام رشته')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'رشته ورزشی',
                'verbose_name_plural': 'رشته\u200cهای ورزشی',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='club',
            name='sports',
            field=models.ManyToManyField(blank=True, related_name='clubs', to='clubs.sport', verbose_name='رشته\u200cهای ورزشی'),
        ),
    ]
